### ISSUE TITLE
library Tc3_XPlanarStandard is missing...

### ISSUE THREAD

**Issue by runtimevic** [Beckhoff-USA-Community/TwinCAT-Xbox-Controller-Service#1]
Hello:
Library Tc3_XPlanarStandard is missing where can i download or find it
if you can send it to my email: victorduranm@hotmail.com
thank you very much, Victor
<img width="235" alt="Library_Tc3_XPlanarStandard_missing" src="https://user-images.githubusercontent.com/53791834/194713964-0e4e8fa3-7427-4d63-b026-3703f0a76711.PNG">

**Comment by 0w8States** [comment]
@runtimevic The Tc3_XPlanarStandard is used for our XPlanar Base Framework project. If you need a copy you should reach out to your local applications or sales engineer. For that specific library Beckhoff needs an MNDA in place before distribution.

This brings up a good point though.. I'll try to rework it to use the PlanarMotion library that comes with the XPlanar install from the website.

**Comment by runtimevic** [comment]
Thank you...👍😉
